# Generated by Django 5.0.14 on 2026-05-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('gym', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_per_session', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_cycle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('group', 'Групповое'), ('individual', 'Индивидуальное')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('clients', models.ManyToManyField(related_name='enrolled_groups', through='enrollments.GroupEnrollment', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Главный'), ('assistant', 'Ассистент')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_instructors', to='workouts.group')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_instructors', to='users.instructor')),
            ],
            options={
                'unique_together': {('group', 'instructor')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='instructors',
            field=models.ManyToManyField(related_name='groups', through='workouts.GroupInstructor', to='users.instructor'),
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='workouts.group')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gym.gymhall')),
                ('instructors', models.ManyToManyField(related_name='scheduled_classes', to='users.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='workout_type',
            field=models.ForeignKey(limit_choices_to={'category': 'group'}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='workouts.workouttype'),
        ),
    ]
