# Generated by Django 5.0.14 on 2026-05-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('cardio', 'Кардио'), ('strength', 'Силовой'), ('functional', 'Функциональный')], max_length=20)),
                ('last_maintenance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GymHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HallEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_equipments', to='gym.equipment')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_equipments', to='gym.gymhall')),
            ],
            options={
                'unique_together': {('hall', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='gymhall',
            name='equipment',
            field=models.ManyToManyField(related_name='halls', through='gym.HallEquipment', to='gym.equipment'),
        ),
    ]
