# Generated by Django 5.0.14 on 2026-05-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('users', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupenrollment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.client'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='workouts.group'),
        ),
        migrations.AddField(
            model_name='individualsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='users.client'),
        ),
        migrations.AddField(
            model_name='individualsession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='individualsession',
            name='workout_type',
            field=models.ForeignKey(limit_choices_to={'category': 'individual'}, on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='workouts.workouttype'),
        ),
        migrations.AlterUniqueTogether(
            name='groupenrollment',
            unique_together={('client', 'group')},
        ),
    ]
