# Generated by Django 5.0.14 on 2026-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(default='Общие', max_length=80)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
    ]
