# Generated by Django 5.0.14 on 2026-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_term_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['order', 'full_name']},
        ),
        migrations.AddField(
            model_name='contactperson',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
