# Generated by Django 5.0.14 on 2026-05-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contactperson_options_contactperson_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. зарплата (BYN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мин. зарплата (BYN)'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='role',
            field=models.CharField(help_text='Описание работы сотрудника', max_length=150),
        ),
    ]
