# Generated by Django 5.0.14 on 2026-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_term_alter_contactperson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
