# Generated by Django 5.0.14 on 2026-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_vacancy_salary_max_remove_vacancy_salary_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('category', models.CharField(choices=[('fitness', 'Фитнес'), ('nutrition', 'Питание'), ('workout', 'Тренировки'), ('health', 'Здоровье'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
                'ordering': ['term'],
            },
        ),
    ]
